POST http://localhost:8080/got-character HTTP/1.1
Content-Type: application/json

 {
    "firstName": "Daenerys",
    "lastName": "Targaryen",
    "fullName": "Daenerys Targaryen",
    "title": "Mother of Dragons",
    "family": "House Targaryen",
    "image": "daenerys.jpg",
    "imageUrl": "https://thronesapi.com/assets/images/daenerys.jpg"
  }

###

GET http://localhost:8080/got-character HTTP/1.1